

program:
  - name: pid1
    type: PID
    init_args:
      SV: 1.0
      MV: 0.0
      PB: 120
      TI: 30
      TD: 0.15
    expression: pid1.execute(PV=tank1.level, SV=sin1.out)
  - name: sin1
    type: SINE_WAVE
    init_args:
      amplitude: 100.0
      period: 1200
      phase: 0.0
    expression: sin1.execute()
  - name: tank1
    type: CYLINDRICAL_TANK
    init_args:
      height: 10.0
      radius: 1.0
      initial_level: 0.0
    expression: tank1.execute(valve_opening=valve1.current_opening)
  - name: valve1
    type: VALVE
    init_args:
      min_opening: 0.0
      max_opening: 100.0
      step: 0.1
      full_travel_time: 10.0
    expression: valve1.execute(target_opening=pid1.MV)
  - name: non_sense_1
    type: RANDOM
    init_args:
      L: 0.0
      H: 100.0
      max_step: 3.0
    expression: non_sense_1.execute()
  - name: non_sense_2
    type: RANDOM
    init_args:
      L: 0.0
      H: 100.0
      max_step: 3.0
    expression: non_sense_2.execute()
  - name: non_sense_3
    type: Variable
    expression: non_sense_3 = non_sense_1[-30] + 2 * non_sense_2
  - name: non_sense_4
    type: Variable
    expression: non_sense_4 = sin(non_sense_3)
    